### ISSUE TITLE
SSR订阅中的链接请遵循标准协议

### ISSUE THREAD

**Issue by liesauer** [voken100g/AutoSSR#1]
```text
string(136) "stable1.local:443:origin:aes-256-cfb:plain:aHR0cHM6Ly90Lm1lL2F1dG9zc3I=/?remarks=5YWN6LS5IFNTUiDlhaznm4rliIbkuqs=&group=dC5tZS9hdXRvc3Ny"
string(63) "remarks=5YWN6LS5IFNTUiDlhaznm4rliIbkuqs=&group=dC5tZS9hdXRvc3Ny"
```
如上面所写，SSR链接没有使用urlsafe base64，生成出来的链接并不能被客户端正确解析！

标准的链接如下，全是采用urlsafe base64！
```text
ssr://host:port:protocol:method:obfs:urlsafebase64pass/?obfsparam=urlsafebase64&protoparam=&remarks=urlsafebase64&group=urlsafebase64&udpport=0&uot=1
```

参考资料
[标准Base64编码,URLSafe模式(OC,Android,Java,PHP)](https://www.jianshu.com/p/014718b034c7)

**Comment by vnMichael** [comment]
Thank you very much.

This problem caused by `=`

Already update and fixed, in [qwert](https://github.com/voken100g/python-qwert/commit/9d348a6625548d1a335ae0f28c0d35c221506d52) and [shadowsocksr-tools
](https://github.com/voken100g/python-shadowsocksr-tools/commit/5db9396eaa63148781e7cf1bec82b03b507d60c4)

If you are have an ETH address, leave a message below, we will send you some [Voken](http://voken.io/en/latest/whitepaper/application_description_and_economic_model.html#voken) for rewards.

**Comment by lymansnow** [comment]
Test passed, for:

- shadowrocket on iOS
- SSRR on Android
- ShadowsocksR on windows

Issue closed.

**Comment by liesauer** [comment]
@vnMichael yes, tks. `0x9d3295F0E21313F7d51F27a3Aac47Cf98C39b747`

**Comment by vnMichael** [comment]
> 
> 
> @vnMichael yes, tks. `0x9d3295F0E21313F7d51F27a3Aac47Cf98C39b747`

Already transferred.

TxHash [0xaf6d2de1d037d409a764f3590cda3ec1620ea3178cc42c40976ac92948075a8b](https://etherscan.io/tx/0xaf6d2de1d037d409a764f3590cda3ec1620ea3178cc42c40976ac92948075a8b)

First issue, first reward for dvlper, 1,000,000 Voken for you.

Thank you too.
